version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    groups:
      nuget-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
      day: monday
      time: "09:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"